export const GAMESTATE = {
  BET: 'BET',
  DEAL: 'DEAL',
  CHECKFORWINNER: 'CHECKFORWINNER',
  PLAYERTURN: 'PLAYERTURN',
  DEALERTURN: 'DEALERTURN',
  DECLAREWINNER: 'DECLAREWINNER',
  GAMEOVER: 'GAMEOVER',
};

export const WINNER = {
  PLAYER: 'PLAYER',
  DEALER: 'DEALER',
  TIE: 'TIE',
};
